@startuml
left to right direction

object Account
object Contact
object Case
object Service_Division__c
object User
object Group_Queue
object Knowledge__kav
object ContentVersion
object ContentDocumentLink
object CaseMilestone
object Integration_Error__c
object Migration_Batch__c
object Case_Routing_Rule__mdt

Account "1" --> "*" Contact
Contact "1" --> "*" Case
Service_Division__c "1" --> "*" Case
User "1" --> "*" Case : agent ownership
Group_Queue "1" --> "*" Case : queue ownership
Case "1" --> "*" ContentDocumentLink
ContentVersion "1" --> "*" ContentDocumentLink
Case "1" --> "*" CaseMilestone
Knowledge__kav "*" .. "*" Case : article usage
Integration_Error__c "*" --> "0..1" Case
Migration_Batch__c "1" .. "*" Case : migrated records
Case_Routing_Rule__mdt ..> Case : assignment attributes

@enduml
