@startuml

package "Presentation Layer" {

[Experience Cloud]

[LWC]

}

package "Application Layer" {

[Record-Triggered Flow]

}

package "Business Layer" {

[GrantApplicationService]

[ContactMatchingService]

[GrantDisbursementService]

[GrantConfigurationService]

[GrantSupportOptionService]

[GrantExceptionService]

}

package "Persistence Layer" {

[Trigger Framework]

[Salesforce Objects]

}

package "Integration Layer" {

[REST Client]

[Named Credential]

[GrantIntegrationService]

}

package "External Systems" {

[Master Data System]

}

[Experience Cloud] --> [LWC]

[LWC] --> [GrantApplicationService]

[Record-Triggered Flow] --> [GrantDisbursementService]

[GrantApplicationService] --> [ContactMatchingService]

[GrantApplicationService] --> [GrantSupportOptionService]

[GrantApplicationService] --> [GrantDisbursementService]

[GrantDisbursementService] --> [GrantConfigurationService]

[GrantDisbursementService] --> [Trigger Framework]

[Trigger Framework] --> [Salesforce Objects]

[GrantExceptionService] --> [Salesforce Objects]

[GrantIntegrationService] --> [REST Client]

[REST Client] --> [Named Credential]

[Named Credential] --> [Master Data System]

@enduml
