@startuml
left to right direction

state "Pending Approval" as PendingApproval

[*] --> Submitted

Submitted --> PendingApproval

PendingApproval --> Approved

PendingApproval --> Rejected

Approved --> Active

Active --> Completed

Completed --> Closed

Rejected --> Closed

@enduml
