@startuml
left to right direction

state "Application Reference Cleared" as ApplicationReferenceCleared

[*] --> Scheduled

Scheduled --> Disbursed

Scheduled --> Recalculated

Recalculated --> Scheduled

Disbursed --> Completed

Completed --> ApplicationReferenceCleared

@enduml
