@startuml

entity Grant_Support_Option__mdt {

DeveloperName

MasterLabel

Monthly_Amount__c

Duration_Months__c

Sort_Order__c

Active__c

}

entity Grant_Configuration__mdt {

Grant_Type__c

Maximum_Amount__c

Income_Threshold__c

Minimum_Age__c

Maximum_Age__c

Priority__c

Active__c

}

entity Grant_Error_Message__mdt {

DeveloperName

Message__c

Category__c

Active__c

}

@enduml
