@startuml

package "Presentation Layer" {

component "Experience Cloud"

component "Lightning Web Components"

}

package "Application Layer" {

component "Before-Save Lifecycle Flow"

component "After-Save Notification Flow"

}

package "Business Services" {

component "GrantApplicationService"

component "ContactMatchingService"

component "GrantDisbursementService"

component "GrantConfigurationService"

component "GrantSupportOptionService"

component "GrantApplicationBulkUploadService"

}

package "Persistence Layer" {

component "Trigger Handler"

component "Repository"

component "Grant Application"

}

database "Salesforce Database"

"Experience Cloud" --> "Lightning Web Components"

"Lightning Web Components" --> "GrantApplicationService"

"Before-Save Lifecycle Flow" --> "Salesforce Database"

"After-Save Notification Flow" --> "Grant Application"

"GrantApplicationService" --> "ContactMatchingService"

"GrantApplicationService" --> "GrantSupportOptionService"

"GrantApplicationService" --> "GrantDisbursementService"

"GrantApplicationBulkUploadService" --> "GrantDisbursementService"

"GrantDisbursementService" --> "Trigger Handler"

"Trigger Handler" --> Repository

Repository --> "Salesforce Database"

@enduml
