@startuml
hide empty members
left to right direction

object "GA Portal.page" as PortalPage
object "GA PortalController.cls" as PortalCtrl

map "GA Form.js" as GAForm{
    1 => submitApplication(dto)
    2 => wiredSupportOptions
    3 => wiredClientMessages
}
map "GA Controller.cls" as GACtrl {
    1 => submitApplication(GrantDTO)
    2 => getActiveSupportOptions()
    3 => getActiveGrantTypes()
}

package Services {
    map "GrantConfigurationService.cls" as ConfService {
        1 => getActiveGrantTypes()
        2 => getActiveOptions()
    }

    map "GrantSupportOptionService.cls" as OptService{
        1 => getActiveOptions()
    }
    map "GrantExceptionService.cls" as ExcService {
        1 => getMessage(String, String)
    }
    object "GrantDisbursementService.cls" as DisService

    map "GA Services.cls" as GAService <<wo sharing>>{
        1 => submitApplication(GrantDTO)
        2 => validateApplicantRequest(GrantDTO)
    }

    map "ContactMatchingServices.cls" as MatchService <<wo sharing>>{
        1 => upsertApplicantByPhone(GrantDTO)
    }
}

database Objects{
    object Contact
    object Grant_Application__c
}

package EnqueueJob{
    object "GrantApplicationGuestUpdateJob.cls" as GuestUpdJob
    object "GrantApplicationApplicantLinkJob.cls" as AppLinkJob
}

package Repo{
    map "GrantApplicationRepository.cls" as GARepo{
        1 =>
    }
    map "ContactRepository.cls" as ContactRepo <<wo sharing>>{
        1 => getByPhone(String)
    }
}

PortalPage --> PortalCtrl : GrantDTO
PortalCtrl --> GAService::1

GAForm::1 -[#blue]-> GACtrl::1 : GrantDTO
GACtrl::1 -[#blue]-> GAService::1
GACtrl::2 --> ConfService::2

GAService::1 --> OptService::1
GAService::1 -[#blue]-> MatchService::1
GAService::1 --> GARepo : save()
GAService::1 --> DisService : recalculateForApplicationIds()
GAService::1 --> EnqueueJob : System.enqueueJob()
GAService::2 --> ExcService::1

MatchService::1 -[#blue]-> ContactRepo::1

ContactRepo::1 -[#red]--> Contact
@enduml