@startuml

start

:Execute Business Logic;

if (Success?) then (Yes)

:Commit Transaction;

stop

else

:Capture Exception;

:Resolve friendly message from Grant_Error_Message__mdt;

:Rollback Transaction;

:Return Friendly Message;

stop

endif

@enduml
